name: Build and Upload Asset

on:
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

jobs:
# Linters
  pre-flight-check:
    runs-on: ubuntu-latest
    outputs:
      release-id: ${{ steps.check-release-id.outputs.release_id }}
    steps:
      - name: Check Release ID
        id: check-release-id
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "Running pre-flight check"
          else
            exit 0
          fi
          if [ -n "${{ github.event.release.id }}" ]; then
            echo "Release ID: ${{ github.event.release.id }}"
            echo "release_id=${{ github.event.release.id }}" >> "$GITHUB_OUTPUT"
          else
            echo "Failed to fetch current release id, trying to fetch externally"
            release_id=$(curl -s -X GET \
              -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/latest" | \
              jq -r ".id")
            if [ -n "$release_id" ]; then
              echo "Release ID: ${{ github.event.release.id }}"
              echo "release_id=$release_id" >> "$GITHUB_OUTPUT"
            else
              echo "Release ID not available in the event."
              exit 1
            fi
          fi
  lint-frontend:
    needs: pre-flight-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: make lint-frontend
  lint-backend:
    needs: pre-flight-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.0
      - run: make lint-backend
  lint-commits:
    needs: pre-flight-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: make lint-commits
  lint:
    runs-on: ubuntu-latest
    needs: [lint-frontend, lint-backend, lint-commits]
    steps:
      - run: echo "done"

# Tests
  test-frontend:
    needs: pre-flight-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: make test-frontend
  test-backend:
    needs: pre-flight-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.0
      - run: make test-backend
  test:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    steps:
      - run: echo "done"

# Upload assets for different OS and Architecture
  upload_assets:
    if: ${{ github.event_name == 'release' }}
    needs: [lint, test, pre-flight-check]
    strategy:
      matrix:
        platform:
          # Naming Convention: {operating_system}-{architecture}-{package_name}.{archive_format}
          # macOS - 2
          - release_for: macOS-amd64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: filebrowser
            name: darwin-amd64-filebrowser.tar.gz
            pkg-name: darwin-amd64-filebrowser
            command: build

          - release_for: macOS-arm64
            os: macOS-latest
            target: arm64-apple-darwin
            bin: filebrowser
            name: darwin-arm64-filebrowser.tar.gz
            pkg-name: darwin-arm64-filebrowser
            command: build

# # GitHub doesn't have runners available for FreeBSD: https://github.com/actions/runner/issues/385
#          # freebsd - 3
#          - release_for: freebsd-386
#            os: freebsd-latest
#            target: i386-unknown-freebsd
#            bin: filebrowser
#            name: freebsd-386-filebrowser.tar.gz
#            pkg-name: freebsd-386-filebrowser
#            command: build
#
#          - release_for: freebsd-amd64
#            os: freebsd-latest
#            target: x86_64-unknown-freebsd
#            bin: filebrowser
#            name: freebsd-amd64-filebrowser.tar.gz
#            pkg-name: freebsd-amd64-filebrowser
#            command: build
#
#          - release_for: freebsd-arm64
#            os: freebsd-latest
#            target: aarch64-unknown-freebsd
#            bin: filebrowser
#            name: freebsd-arm64-filebrowser.tar.gz
#            pkg-name: freebsd-arm64-filebrowser
#            command: build

          # linux - 7
          - release_for: linux-386
            os: ubuntu-20.04
            target: i686-unknown-linux-gnu
            bin: filebrowser
            name: linux-386-filebrowser.tar.gz
            pkg-name: linux-386-filebrowser
            command: build

          - release_for: linux-amd64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: filebrowser
            name: linux-amd64-filebrowser.tar.gz
            pkg-name: linux-amd64-filebrowser
            command: build

          - release_for: linux-arm64
            os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
            bin: filebrowser
            name: linux-arm64-filebrowser.tar.gz
            pkg-name: linux-arm64-filebrowser
            command: build

          - release_for: linux-armv5
            os: ubuntu-20.04
            target: armv5te-unknown-linux-gnueabi
            bin: filebrowser
            name: linux-armv5-filebrowser.tar.gz
            pkg-name: linux-armv5-filebrowser
            command: build

          - release_for: linux-armv6
            os: ubuntu-20.04
            target: armv6-unknown-linux-gnueabihf
            bin: filebrowser
            name: linux-armv6-filebrowser.tar.gz
            pkg-name: linux-armv6-filebrowser
            command: build

          - release_for: linux-armv7
            os: ubuntu-20.04
            target: armv7-unknown-linux-gnueabihf
            bin: filebrowser
            name: linux-armv7-filebrowser.tar.gz
            pkg-name: linux-armv7-filebrowser
            command: build

          - release_for: linux-riscv64
            os: ubuntu-20.04
            target: riscv64gc-unknown-linux-gnu
            bin: filebrowser
            name: linux-riscv64-filebrowser.tar.gz
            pkg-name: linux-riscv64-filebrowser
            command: build

          # windows
          - release_for: windows-386
            os: windows-latest
            target: i686-pc-windows-msvc
            bin: filebrowser.exe
            name: windows-386-filebrowser.zip
            pkg-name: windows-386-filebrowser
            command: build

          - release_for: windows-amd64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: filebrowser.exe
            name: windows-amd64-filebrowser.zip
            pkg-name: windows-amd64-filebrowser
            command: build

          - release_for: windows-arm64
            os: windows-latest
            target: arm64-pc-windows-msvc
            bin: filebrowser.exe
            name: windows-arm64-filebrowser.zip
            pkg-name: windows-arm64-filebrowser
            command: build

          - release_for: windows-armv5
            os: windows-latest
            target: armv5-pc-windows-msvc
            bin: filebrowser.exe
            name: windows-armv5-filebrowser.zip
            pkg-name: windows-armv5-filebrowser
            command: build

          - release_for: windows-armv6
            os: windows-latest
            target: armv6-pc-windows-msvc
            bin: filebrowser.exe
            name: windows-armv6-filebrowser.zip
            pkg-name: windows-armv6-filebrowser
            command: build

          - release_for: windows-armv7
            os: windows-latest
            target: armv7-pc-windows-msvc
            bin: filebrowser.exe
            name: windows-armv7-filebrowser.zip
            pkg-name: windows-armv7-filebrowser
            command: build

    name: Upload asset for ${{ matrix.platform.release_for }}
    runs-on: ${{ matrix.platform.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.0
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build Essentials
        run: |
          SHELL="/usr/bin/env bash"
          BASE_PATH="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
          VERSION=$(git describe --tags --always --match=v* 2> /dev/null || cat "$BASE_PATH/.version" 2> /dev/null || echo v0)
          VERSION_HASH=$(git rev-parse HEAD)
          go() {
              GOGC=off go "$@"
          }
          MODULE=$(env GO111MODULE=on go list -m)
          TOOLS_DIR="$BASE_PATH/tools"
          TOOLS_BIN="$TOOLS_DIR/bin"
          mkdir -p "$TOOLS_BIN"
          export PATH="$TOOLS_BIN:$PATH"
          LDFLAGS+="-X \"$MODULE/version.Version=$VERSION\" -X \"$MODULE/version.CommitSHA=$VERSION_HASH\""
        shell: bash

      - name: Build Frontend
        run: cd frontend && npm ci && npm run build
        shell: bash

      - name: Build Backend
        run: go build -ldflags "$LDFLAGS" -o .
        shell: bash

      - name: Copy Artifact (Windows)
        if: ${{ matrix.platform.os == 'windows-latest' }}
        run: |
          mkdir -p ${{ matrix.platform.pkg-name }}
          cp ${{ matrix.platform.bin }} ${{ matrix.platform.pkg-name }}/${{ matrix.platform.bin }}
          Compress-Archive -DestinationPath ${{ matrix.platform.name }} -Path ${{ matrix.platform.pkg-name }}/

      - name: Copy Artifact (macOS/Linux/RaspberryPi)
        if: ${{ matrix.platform.os != 'windows-latest' }}
        run: |
          mkdir -p ${{ matrix.platform.pkg-name }}
          cp ${{ matrix.platform.bin }} ${{ matrix.platform.pkg-name }}/${{ matrix.platform.bin }}
          tar -zcvf ${{ matrix.platform.name }} ${{ matrix.platform.pkg-name }}/

      - name: Upload Asset
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @"${{ matrix.platform.name }}" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ needs.pre-flight-check.outputs.release-id }}/assets?name=${{ matrix.platform.name }}"
        shell: bash
