name: main

on:
  release:
    types: [published]

jobs:
# linters
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: make lint-frontend
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.0
      - run: make lint-backend
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: make lint-commits
  lint:
    runs-on: ubuntu-latest
    needs: [lint-frontend, lint-backend, lint-commits]
    steps:
      - run: echo "done"

# tests
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: make test-frontend
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.0
      - run: make test-backend
  test:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    steps:
      - run: echo "done"

  upload_assets:
    needs: [lint, test]
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: filebrowser
            name: FileBrowser-Linux-x86_64.tar.gz
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: filebrowser.exe
            name: FileBrowser-Windows-x86_64.zip
            command: build

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: filebrowser
            name: FileBrowser-Darwin-x86_64.tar.gz
            command: build

          - release_for: RaspberryPi
            os: ubuntu-20.04
            target: arm-unknown-linux-gnueabihf
            bin: filebrowser
            name: FileBrowser-RaspberryPi.tar.gz
            command: build

    name: Upload asset for ${{ matrix.platform.release_for }}
    runs-on: ${{ matrix.platform.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.0
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: release
        run: |
          SHELL="/usr/bin/env bash"
          BASE_PATH="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
          VERSION=$(git describe --tags --always --match=v* 2> /dev/null || cat "$BASE_PATH/.version" 2> /dev/null || echo v0)
          VERSION_HASH=$(git rev-parse HEAD)
          go() {
              GOGC=off go "$@"
          }
          MODULE=$(env GO111MODULE=on go list -m)
          TOOLS_DIR="$BASE_PATH/tools"
          TOOLS_BIN="$TOOLS_DIR/bin"
          mkdir -p "$TOOLS_BIN"
          export PATH="$TOOLS_BIN:$PATH"
          LDFLAGS+="-X \"$MODULE/version.Version=$VERSION\" -X \"$MODULE/version.CommitSHA=$VERSION_HASH\""
          cd frontend && npm ci && npm run build
          go build -ldflags "$LDFLAGS" -o .
        shell: bash

      - name: Copy Artifacts (Windows)
        if: ${{ matrix.platform.os == 'windows-latest' }}
        run: |
          mkdir -p ${{ matrix.platform.name }}
          cp ${{ matrix.platform.bin }} ${{ matrix.platform.name }}/${{ matrix.platform.bin }}
          Compress-Archive -DestinationPath ${{ matrix.platform.name }} -Path ${{ matrix.platform.name }}/

      - name: Copy Artifacts (macOS/Ubuntu)
        if: ${{ matrix.platform.os != 'windows-latest' }}
        run: |
          mkdir -p ${{ matrix.platform.name }}
          cp ${{ matrix.platform.bin }} ${{ matrix.platform.name }}/${{ matrix.platform.bin }}
          tar -zcvf ${{ matrix.platform.name }} ${{ matrix.platform.name }}/

      - name: Upload Asset to Release
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @"${{ matrix.platform.name }}" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=${{ matrix.platform.name }}"
        shell: bash
